import { useState } from 'react';
import { LikertScale } from '../components/LikertScale';
import { PageShell } from '../components/PageShell';
import { PrimaryButton } from '../components/PrimaryButton';
import { ProgressBar } from '../components/ProgressBar';
import { QuestionCard } from '../components/QuestionCard';
import type { PostQuestionnaire } from '../types/experiment';

export function PostQuestionnairePage({ initial, onFinish }: { initial?: PostQuestionnaire; onFinish: (data: PostQuestionnaire) => void }) {
  const [overallEase, setOverallEase] = useState(initial?.overallEase); const [naturalness, setNaturalness] = useState(initial?.naturalness); const [appearanceCompatibility, setCompatibility] = useState(initial?.appearanceCompatibility); const [comment, setComment] = useState(initial?.comment ?? ''); const [attempted, setAttempted] = useState(false);
  const valid = Boolean(overallEase && naturalness && appearanceCompatibility);
  function submit() { setAttempted(true); if (valid) onFinish({ overallEase: overallEase!, naturalness: naturalness!, appearanceCompatibility: appearanceCompatibility!, comment: comment.trim() }); }
  return <PageShell width="max-w-4xl"><ProgressBar value={90} /><div className="mb-7 mt-6"><p className="text-sm font-bold text-brand-600">Última etapa</p><h1 className="mt-1 text-3xl font-extrabold text-ink">Para finalizar...</h1><p className="mt-2 text-slate-600">Pensando em todas as expressões que você acabou de observar, responda às perguntas abaixo.</p></div><div className="space-y-5"><QuestionCard title="De modo geral, foi fácil compreender as expressões faciais do robô?"><LikertScale name="overallEase" value={overallEase} onChange={setOverallEase} lowLabel="Muito difícil" highLabel="Muito fácil" /></QuestionCard><QuestionCard title="De modo geral, quão naturais pareceram as expressões faciais do robô?"><LikertScale name="naturalness" value={naturalness} onChange={setNaturalness} lowLabel="Nada naturais" highLabel="Muito naturais" /></QuestionCard><QuestionCard title="De modo geral, você considera que as expressões faciais combinam com a aparência do robô?"><LikertScale name="compatibility" value={appearanceCompatibility} onChange={setCompatibility} lowLabel="Não combinam" highLabel="Combinam muito" /></QuestionCard><QuestionCard title="Se desejar, deixe algum comentário ou sugestão sobre as expressões faciais do Roboldo."><label className="sr-only" htmlFor="comment">Comentário opcional</label><textarea id="comment" value={comment} onChange={(e) => setComment(e.target.value)} maxLength={1000} rows={4} className="w-full resize-y rounded-xl border-2 border-slate-200 p-4 outline-none transition focus:border-brand-600 focus:ring-4 focus:ring-brand-100" placeholder="Comentário opcional" /></QuestionCard></div>{attempted && !valid && <p role="alert" className="mt-5 rounded-xl bg-amber-50 p-3 text-sm font-semibold text-amber-800">Responda às três escalas para continuar.</p>}<PrimaryButton fullWidth className="mt-5" onClick={submit}>Finalizar participação</PrimaryButton></PageShell>;
}
